# **************************************************************************************************************
#
#  Copyright 2020-2023 Robert Bosch GmbH
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# **************************************************************************************************************
#
# RobotLog2DB - pyproject.toml
#
# --------------------------------------------------------------------------------------------------------------

[build-system]
requires = ["setuptools==79.0.1", "wheel", "colorama==0.4.6", "pypandoc_binary==1.15", "PythonExtensionsCollection"]
build-backend = "setuptools.build_meta"

[project]
name = "robotframework-robotlog2db"
version = "1.5.4"
description = "Imports robot result(s) to TestResultWebApp database"
authors = [
   {name = "Tran Duy Ngoan", email = "Ngoan.TranDuy@vn.bosch.com"}
]
maintainers = [
   {name = "Tran Duy Ngoan", email = "Ngoan.TranDuy@vn.bosch.com"}
]
license = "Apache-2.0"
requires-python = ">=3.13"
dependencies = [
   "colorama",
   "robotframework",
   "lxml",
   "TestResultDBAccess"
]

[project.urls]
Homepage = "https://github.com/test-fullautomation/robotframework-robotlog2db"

[project.scripts]
RobotLog2DB = "RobotLog2DB.robotlog2db:RobotLog2DB"

[tool.setuptools]
packages = ["RobotLog2DB", "RobotLog2DB.xsd"]

[tool.setuptools.package-data]
RobotLog2DB = ["*.pdf", "xsd/*.xsd"]
